import { Inter } from "next/font/google";
import "./globals.css";
import { LoggedProvider } from "../context/loggedContext.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Juampi app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <LoggedProvider>{children}</LoggedProvider>
      </body>
    </html>
  );
}
